title: Kris Kahler
description: GeoGeek
#logo: kk3.jpg
# description: text below image
show_downloads: true
theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag #Add SEO plugin
email: kkahler190@gmail.com
